### ISSUE TITLE
frontend url

### ISSUE THREAD

**Issue by JarkoeSoLnze** [vova07/yii2-start#103]
Hello 

I use gii for crud generator for "product" (frontend)
and I try to open frontend/product/index 
or frontend/product/index/

Not Found (#404)
Unable to resolve the request "frontend/product/index".

I try without "frontend" and I get 

Not Found (#404)
Page not found.

Strucrure
frontend
-controllers
---ProductController
Models
-Product
-ProductSearch
Views
-Product
--- index
---...
---update

ProductController
namespace app\controllers;

Whats wrong? Thanks

**Comment by joker58** [comment]
Добрый день
Выловил точно такую же ошибку
![15952646-8465-11e4-8b58-85ddb76d52a4](https://cloud.githubusercontent.com/assets/2201178/8811887/9f0f53cc-3001-11e5-9f6d-b665f5702d50.png)
В конфиге backend/main.php
'rules' => [
 '' => 'admin/default/index',
 '<_c>/<_a>' => '<_c>/<_a>'

В контроллере прописан неймспейс 
namespace backend\controllers;

Но если заменить неймспейс на !!!!
namespace app\controllers;
то все отлично начинает работать http://test.ru/backend/citys/index/
Что довольно странно, и противоречит советам выше 0_o
Спасибо за помощь

**Comment by vova07** [comment]
@joker58 добавьте в `backend/config/main.php` контроллер нэймспэйс: `'controllerNamespace' => 'backend\controllers'` должно помочь!

If somebody still have the same issue, you must add `'controllerNamespace' => 'backend\controllers'` to `backend/config/main.php` file.

**Comment by joker58** [comment]
Спасибо за помощь! Это действительно сработало!
