### ISSUE TITLE
Bad Request (#400) on /backend/users/default/update/?id=1

### ISSUE THREAD

**Issue by carlos-andres** [vova07/yii2-start#110]
Good Day, 

i try to update admin profile, just some information and avatar picture and get´s this error, in attachments are all details. also i try to use the solution on issue #88  and not work.

![users2](https://cloud.githubusercontent.com/assets/5489747/5417988/a4886832-820c-11e4-99a8-b9735d82553f.png)

![yii debugger](https://cloud.githubusercontent.com/assets/5489747/5417992/a79dad16-820c-11e4-875a-964c20a690de.png)

with the avatar y check 2 things the path and route, an get some information

![avatar2](https://cloud.githubusercontent.com/assets/5489747/5418125/e0a6d686-820d-11e4-9c52-1c6d1cb3fb7b.png)

**Comment by lcidral** [comment]
I noticed that this happens whenever I make a dump of mysql between one environment and another.
I use mac and also through it.
