### ISSUE TITLE
yii\i18n\PhpMessageSource::loadMessages on /backend/users/default/index/

### ISSUE THREAD

**Issue by carlos-andres** [vova07/yii2-start#111]
Good day, i like report this error, thanks in advcance

![messages](https://cloud.githubusercontent.com/assets/5489747/5420114/e42ad764-821f-11e4-9a4f-6770123f9499.png)

**Comment by janareit** [comment]
I get the same error with blank install.

**Comment by vova07** [comment]
#120 and #101

**Comment by vova07** [comment]
Fixed in https://github.com/vova07/yii2-start-themes/commit/efd69298cfcda7a39df9427cde40974e029770b3
