### ISSUE TITLE
Override models

### ISSUE THREAD

**Issue by nunomaduro** [vova07/yii2-start#112]
Hey,

Override views - OK
Override controllers - OK
Override models - i can't do that.

Question: What is the best option to override models ?

**Comment by timmy78** [comment]
I don't understand how to override controllers, views and models; can you show me an example please ? :(

I want to override the backend login view and the backend GuestController.

I just want to add a captcha in backend login. There is no documentation for these things...

I did something like this : 

```
'view' => [
  //'theme' => 'vova07\themes\admin\Theme'
  'theme' => [
    'pathMap' => [
      '@vova07/users/views/backend/guest' => '@backend/views/users/guest'
    ],
  ],
],
```

Thanks !

**Comment by nunomaduro** [comment]
The best thing is not that. You can create your own modules that extend from vova07 modules. And after that u can override whatever you want.
