### ISSUE TITLE
blog comment cannot handle alias from settings

### ISSUE THREAD

**Issue by golles** [vova07/yii2-start#119]
I've the following config in my frontend main:

```
'users' => [
    'avatarUrl' => '@web/statics/web/users/avatars/',
],
```

The alias is not parsed in the comments module.

You should update the following file

yii2-start-comments-module/widgets/views/_index_item.php#19 

change:

```
<img src="<?= $avatar ?>" class="avatar img-circle width-50" alt="<?= $comment->author->profile->fullName ?>"/>
```

to

```
<img src="<?= Url::to($avatar) ?>" class="avatar img-circle width-50" alt="<?= $comment->author->profile->fullName ?>"/>
```

**Comment by vova07** [comment]
URL aliases are available starting `2.0.2` version, so, I'll do a little update to fix some specific moments.
Thanks!

**Comment by golles** [comment]
Great I'll post some more issues which you can maybe fix as well

**Comment by vova07** [comment]
Thanks!
