### ISSUE TITLE
Missing English translation folder/file

### ISSUE THREAD

**Issue by golles** [vova07/yii2-start#120]
Every time I load a backend page I get this error:

```
The message file for category 'vova07/themes/admin' does not exist: some_path/vendor/vova07/yii2-start-themes/admin/messages/en/vova07/themes/admin.php
```

For frontend as well:
```
The message file for category 'vova07/themes/site' does not exist: some_pathl/vendor/vova07/yii2-start-themes/site/messages/en/vova07/themes/site.php
```

There is only pr-BR and ru messages in that module

**Comment by vova07** [comment]
Fixed in https://github.com/vova07/yii2-start-themes/commit/efd69298cfcda7a39df9427cde40974e029770b3

**Comment by golles** [comment]
It still gives the same error. I guess it really needs the files.

**Comment by vova07** [comment]
Do you really have the last version?
Can you check if your `yii2-start-themes` module has the last [`bootstrap`](https://github.com/vova07/yii2-start-themes/commit/efd69298cfcda7a39df9427cde40974e029770b3) file with `false` value for `forceTranslation` attribute?

**Comment by golles** [comment]
Yes, both site and admin have 'forceTranslation' => false,

**Comment by golles** [comment]
I think this is an issue because I've set 
```
'language' => 'en'
```
in main config file.

I'm also getting 404's for english language files, eg when I'm opening the new blog page:
backend/assets/b75b2961/lang/en.js (Imperavi Redactor)
backend/assets/8cf95688/ui/i18n/datepicker-en.js

If I change the lang to eg Dutch (nl) the errors are gone because the nl files do exist.
