### ISSUE TITLE
Updating themes

### ISSUE THREAD

**Issue by nunomaduro** [vova07/yii2-start#126]
Is possible for you to update the backend template ? 

Because the source of him was updated one day ago - https://github.com/almasaeed2010/AdminLTE

**Comment by vova07** [comment]
I'll try to do that on next weekend.

**Comment by nunomaduro** [comment]
I already update my project, it's easy. You just have to follow:

https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade
