### ISSUE TITLE
German language files

### ISSUE THREAD

**Issue by tonwi** [vova07/yii2-start#128]
I want either upload or send german translation files for all Yii2-start extensions...it is a small tar file (about 7k)...but I cannot find any attachment button.
how should I do?

**Comment by vova07** [comment]
Hi there,
Ideal option is the `Pull Request`, but if it is not a good idea for you, you can send me the `.tar` file via e-mail. My e-mail address: `bazillio07@yandex.ru`. Or you can upload it somewhere and give the download link.
Thanks!

**Comment by vova07** [comment]
Done! 
@tonwi Thank you!
