### ISSUE TITLE
Missing support for multiple Yii2 FileAPI widgets.

### ISSUE THREAD

**Issue by nunomaduro** [vova07/yii2-start#133]
Hey, 

First of all, congratulations, the yii2-start project is fantastic.

Any future plans to make support for multiple Yii2 FileAPI widgets ?

Thank you.

**Comment by vova07** [comment]
Thank you @nunomaduro !
Yes, it's planned, but need more time, too busy ATM.

**Comment by nunomaduro** [comment]
Ok! Meanwhile I will force the user upload a image one by one.
