### ISSUE TITLE
setting-up on windows issues 

### ISSUE THREAD

**Issue by banyx101** [vova07/yii2-start#134]
Dear Vova07, 

I'm facing problems configuring on win7 using Xampp as server environment . My problems I thing are related with point 8. virtualhost config, can you give some hint (workaround) to help me running this great package please. My app can not find bootstrap css, jquery and other paths to assets, and just opens with no style and all wrong pointing links !

thanks in advance :)

**Comment by vova07** [comment]
Hi @banyx101 sorry for late answer.
Unfortunately at the moment I don't have a `windows` machine, and even a `XAMPP`, so I can't give you a concrete advices, but you can google some info about it, for example, [here](https://www.delanomaloney.com/2013/07/10/how-to-set-up-virtual-hosts-using-xampp/) is a mini tutorial for `XAMPP Vhosts` and [here](http://stackoverflow.com/questions/20796726/unable-to-setup-virtual-host-for-windows-8-computer-xampp) is a related question on StackOverflow.
Hope it will be helpful for you!

**Comment by banyx101** [comment]
Thanks for your answer I will follow the instructions and revert if I succeed. 
Best Fabjan

**Comment by banyx101** [comment]
Hi @vova07 , 
Issue resolved thanks for your hint. Solution found in your fist link XAMPP [here](https://www.delanomaloney.com/2013/07/10/how-to-set-up-virtual-hosts-using-xampp/)
Thnx again!
