### ISSUE TITLE
I am getting "assets" folder blank content issue

### ISSUE THREAD

**Issue by hostkerala** [vova07/yii2-start#135]
Failed to load resource: the server responded with a status of 404 (Not Found)
http://yii2.biz.local/assets/f28dce7/js/vendor/jquery.ui.widget.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by vova07** [comment]
Is your `VHOSTS` root configured right? Can you provide your configuration here?

**Comment by hostkerala** [comment]
Thanks, It was my fault.
