### ISSUE TITLE
Some caution with the use of Module->getInstance()

### ISSUE THREAD

**Issue by nunomaduro** [vova07/yii2-start#137]
I think that getInstance function should not be used in your modules. Because for example if I want to create my own modules that extend from your modules that simple function will cause an exception. Because your module is not init in my main.php, only my module.

For example:

```
/**
 * @inheritdoc
 */
public function rules()
{
    return [
        // Name
        ['name', 'match', 'pattern' => Module::getInstance()->patternName],
        // Surname
        ['surname', 'match', 'pattern' => Module::getInstance()->patternSurname]
    ];
}
```

Maybe you should put like this:

```
/**
 * @inheritdoc
 */
public function rules()
{
    return [
        // Name
        ['name', 'match', 'pattern' => '/^[a-zа-яё]+$/iu'],
        // Surname
        ['surname', 'match', 'pattern' => '/^[a-zа-яё]+(-[a-zа-яё]+)?$/iu']
    ];
}
```

**Comment by vova07** [comment]
Yes, I know, and I'm completely agree with you. It will be fixed in next releases. 
Thanks!

**Comment by nunomaduro** [comment]
I already made a pull request to yii2-start-users-module to remove that method. After you aprove you can close this.

**Comment by vova07** [comment]
Thank you!
