### ISSUE TITLE
в backend неправильно строится путь к assets

### ISSUE THREAD

**Issue by pol-den** [vova07/yii2-start#139]
в backend неправильно строится путь к assets: /backend/assets.
вылечил так
`'assetManager' => [ 
    ..
   'baseUrl' => '/assets',
     ],`

**Comment by vova07** [comment]
Очень странно.
Вероятнее всего у вас что-то с рутами не так. 
Убедитесь в том что у вас настройки `VHOSTS` именно такие как предполагается в инструкции по установке.

**Comment by pol-den** [comment]
возможно, но advanced не первый раз ставлю, Ваш вариант решил посмотреть.
использую nginx https://bpaste.net/show/dda05c8d5dd2

**Comment by vova07** [comment]
Попробуйте вот [тут](https://github.com/vova07/yii2-start/blob/master/backend/config/main.php#L31): поменять `baseUrl` на `'baseUrl' => ''`
Должно помочь!

**Comment by pol-den** [comment]
совсем удалил).
Помогло. и из Url ушел лишний /backend/

**Comment by vova07** [comment]
Вот и хорошо!
Закрываю тогда репорт!
