### ISSUE TITLE
Error adding comment to blog entry

### ISSUE THREAD

**Issue by dbd5** [vova07/yii2-start#145]
Hello,

First - thanks for the work you put into this kit.

I have set it up successfully and I'm just testing it out.

I made a new blog entry at the backend and tried to add a comment at the front end but got this message:

Model class is invalid.Invalid model ID

Please advise what could be wrong

Thanks

**Comment by vova07** [comment]
Hi @dbd5 ,
Probably the problem is in comments `models` sections.
Before you'll can comment something, you may first allow that model to be commented.
So the only what you need to do, is to enable commentaries for blog models, in `comments` module.

**Comment by dbd5** [comment]
Thanks for getting back!

However, the models index (domain.com/backend/comments/models/index/) - Enable/Disable comments for installed modules has an entry for blog with a check mark indicating it is already enabled.

**Comment by vova07** [comment]
@dbd5 can you provide a screenshot for that page?

**Comment by dbd5** [comment]
Hi Sir Vasile,

I can now comment on blog entries

I've tried to reproduce the error but it doesn't happen, perhaps this had something to do with the fact that the system was freshly setup with no data. 

I will close the issue for now and let you know if it happens again 

Thanks
