### ISSUE TITLE
Подключение своего модуля

### ISSUE THREAD

**Issue by des1roer** [vova07/yii2-start#148]
есть ли какая нибудь хитрость при подключении своего модуля (ничего сложного, просто модели и круды, отвечающие за примерно одинаковый функционал)

https://toster.ru/q/235514?e=2553094#comment_806161

пытаюсь в yii 2 сделать свой модуль. ложу его в vendor. туда же генерю модель и круд. но сайт говорит что нет такой страницы. в чем может быть подвох

![screenshot_10](https://cloud.githubusercontent.com/assets/10970793/8928043/1f6ce808-3535-11e5-8581-c3976c14565d.png)
![screenshot_12](https://cloud.githubusercontent.com/assets/10970793/8928042/1f68ac34-3535-11e5-87d6-e4f6c89738bf.png)

**Comment by vova07** [comment]
Если вы создаете модуль для общего использования то вместо того чтобы его создавать в вендор папку лучше выделить для него отдельный репозиторий, и использовать компосер для его установки.
Если же модуль нужен в рамках одного проекта, то лучше использовать папку "frontend(backend)/modules" для всех ваших модулей.

Создания модуля заключается в добавлении нужной папки с файлами в `modules` и его подключение в конфигурационом файле. 
А также при использовании дефолтной сборки `Yii2-Start` вам нужно добавить правило в `URL` менеджер чтобы модуль стал доступен по выбранному вами пути, после этого он будет доступен для серфинга.

Удачи!

**Comment by des1roer** [comment]
мне нужен модуль локально. а как тогда правильно настроить юрл менеджер

**Comment by vova07** [comment]
Например чтобы сделать модуль доступным во фронтенде вам нужно в [настройках](https://github.com/vova07/yii2-start/blob/master/frontend/config/main.php#L22) добавить новое правило.
Пример:

``` php
'<_m>/<_c>/<_a>' => '<_m>/<_c>/<_a>'
```

После, модуль станет доступен по такому адресу:
`http://my-site.com/moduleName/controllerName/actionName/` 
Хочу заметить что с дефолтными настройками `/` в конце УРЛ-а обязательно нужно добавить.

**Comment by des1roer** [comment]
слава яйцам )))) спасибо огромное.

**Comment by vova07** [comment]
Пожалуйста!
