### ISSUE TITLE
Использование ваших модулей в basic приложении

### ISSUE THREAD

**Issue by des1roer** [vova07/yii2-start#149]
По сути адвансед для начального уровня избыточен. Но вот реализация у вас больно крутая. Могу ли я подключить модули 

```
    "vova07/yii2-start-base": "*",
    "vova07/yii2-start-themes": "*",
    "vova07/yii2-start-admin-module": "*",
    "vova07/yii2-start-site-module": "*",
    "vova07/yii2-start-users-module": "*",   
    "vova07/yii2-start-rbac-module": "*"
```

в basic шаблон?

**Comment by vova07** [comment]
Вы можете подключить модули в бэйсик, но в таком случае вам нужно будет самому все настроить и допилить. Суть в том что модули заточены под `Yii2-Start`, но их можно использовать и за пределами приложения, но только с хорошей настройкой.

В будущем если будет время, они станут абсолютно независимы от структур и сторонних либ.
