### ISSUE TITLE
Не могу обратиться к контролеру

### ISSUE THREAD

**Issue by des1roer** [vova07/yii2-start#151]
\yii2-start\frontend\config\main.php

```
    'urlManager' => [
        'rules' => [
            '' => 'site/default/index',
            '<_a:(about|contacts|captcha)>' => 'site/default/<_a>',
            '<_m>/<_c>/<_a>' => '<_m>/<_c>/<_a>'
        ]
    ],
```

\yii2-start\common\config\main.php

```
    'urlManager' => [
        'enablePrettyUrl' => true,
        'enableStrictParsing' => false,
        'showScriptName' => true,
        'suffix' => '/'
    ],
```

\yii2-start\frontend\modules\main\controllers\PagesController.php

```
public function actionLol($id)
{
    return $id;
}
```

http://yii2-start/main/pages/lol?id=12  Not Found (#404)

вроде контролер правильно прописан а ошибка. может нужно в urlmanager что изменить?

**Comment by vova07** [comment]
Упустили `/`в конце. Напоминаю что при дефолтных настройках его нужно обязательно прописывать.
Правильная ссылка:
`http://yii2-start/main/pages/lol/?id=12`

**Comment by des1roer** [comment]
thx
