### ISSUE TITLE
Using Gii with yii2-start

### ISSUE THREAD

**Issue by languid01** [vova07/yii2-start#153]
I have installed yii2-start on a WAMP environment, and followed all instructions for the install.

I cannot get GII to work. Do I need to change any configurations to activate gii?

Thanks

**Comment by vova07** [comment]
You need to `init` the `development` environment to use `Gii`, so ensure that you did that.
You also need to add a `url` rule to be able to access the modules. `'<_m>/<_c>/<_a>' => <_m>/<_c>/<_a>'`
After you may be sure that you access the right `url`. Remember that by default all `url` require at the end `/`.

**Comment by languid01** [comment]
Many thanks. I had run init for dev and setup the url rule. I was just 
missing the / !!!

I just knew it would be something simple!!

Many thanks

On 02/08/2015 11:51, Vasile C. wrote:

> You need to |init| the |development| environment to use |Gii|, so 
> ensure that you did that.
> You also need to add a |url| rule to be able to access the modules. 
> |'<_m>/<_c>/<_a>' => <_m>/<_c>/<_a>'|
> After you may be sure that you access the right |url|. Remember that 
> by default all |url| require at the end |/|.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/vova07/yii2-start/issues/153#issuecomment-127009542.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by vova07** [comment]
You're welcome!
