### ISSUE TITLE
Настройка URL

### ISSUE THREAD

**Issue by aripjanovsh** [vova07/yii2-start#31]
Здравствуйте,
А как можно настроить url что-бы frontend/web/index.php был http://sitename.com,
а backend/web/index.php был http://sitename.com/backend
Заранее спасибо за ответ,

**Comment by valery-lavrik** [comment]
по умолчанию такого нет. олазиль весь нет, выручило только это - http://lavrik-v.ru/info/260/YII_2_ADVANCED_htaccess_primer_pravilnoj_nastrojki.html
хотя это не совсем правильное решение, но оно хоть как-то заработало....
