### ISSUE TITLE
Yii-debug не работает

### ISSUE THREAD

**Issue by kybarg** [vova07/yii2-start#4]
Вместо тулбара

<pre>
Not Found (#404): Страница не найдена.
</pre>

В консоли

<pre>
GET http://my-site.com/debug/default/toolbar/?tag=52e3e10d40d70 404 (Not Found) 
</pre>

**Comment by bismoney** [comment]
> ```
> '<_m:debug>/<_c:\w+>/<_a:\w+>' => '<_m>/<_c>/<_a>',
> ```

Спасибо друг. Ты сэкономил мне время) С меня кофе, куда закинуть на кофе денежку?)
