### ISSUE TITLE
The file or directory to be published does not exist

### ISSUE THREAD

**Issue by hdushku** [vova07/yii2-start#74]
exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: C:\wamp\www\yii2-start/vendor\bower/jquery/dist' in C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\AssetManager.php:366
Stack trace:
#0 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\AssetBundle.php(162): yii\web\AssetManager->publish('C:\wamp\www\yii...', Array)
#1 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\AssetManager.php(209): yii\web\AssetBundle->publish(Object(yii\web\AssetManager))
#2 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\AssetManager.php(189): yii\web\AssetManager->loadBundle('yii\web\JqueryA...', Array, true)
#3 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\View.php(284): yii\web\AssetManager->getBundle('yii\web\JqueryA...')
#4 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\View.php(289): yii\web\View->registerAssetBundle('yii\web\JqueryA...', NULL)
#5 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\View.php(289): yii\web\View->registerAssetBundle('yii\bootstrap\B...', NULL)
#6 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\AssetBundle.php(118): yii\web\View->registerAssetBundle('frontend\themes...')
#7 C:\wamp\www\yii2-start\frontend\themes\site\views\layouts\head.php(19): yii\web\AssetBundle::register(Object(yii\web\View))
#8 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\View.php(315): require('C:\wamp\www\yii...')
#9 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\wamp\www\yii...', Array)
#10 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('C:\wamp\www\yii...', Array, NULL)
#11 C:\wamp\www\yii2-start\frontend\themes\site\views\layouts\main.php(18): yii\base\View->render('//layouts/head')
#12 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\View.php(315): require('C:\wamp\www\yii...')
#13 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\wamp\www\yii...', Array)
#14 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\Controller.php(368): yii\base\View->renderFile('C:\wamp\www\yii...', Array, Object(frontend\modules\site\controllers\DefaultController))
#15 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\ErrorAction.php(108): yii\base\Controller->render('error', Array)
#16 [internal function]: yii\web\ErrorAction->run()
#17 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#18 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\Controller.php(150): yii\base\Action->runWithParams(Array)
#19 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\Module.php(462): yii\base\Controller->runAction('error', Array)
#20 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\ErrorHandler.php(79): yii\base\Module->runAction('site/default/er...')
#21 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\ErrorHandler.php(95): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#22 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#23 {main}

Previous exception:
exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\Request.php:188
Stack trace:
#0 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\web\Application.php(75): yii\web\Request->resolve()
#1 C:\wamp\www\yii2-start\vendor\yiisoft\yii2\base\Application.php(371): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 C:\wamp\www\yii2-start\frontend\web\index.php(17): yii\base\Application->run()
#3 {main}

**Comment by nvshivakumar** [comment]
Still i m getting issue,
the file or directory to be published does not exist: D:\wamp\www\yii2/vendor\bower/fullcalendar/dist
  "philippfrenzel/yii2fullcalendar":"*",

**Comment by vova07** [comment]
Could you remove `vendor` directory, and try to install it again?

**Comment by nvshivakumar** [comment]
No, it becomes problem for me because , most of the directories i already
installed (components & widgets) is there any other solution

**Comment by vova07** [comment]
mmmm .... I'm not sure if there is another solution. Maybe you can try to update `asset plugin` by running this command: `php composer.phar global require "fxp/composer-asset-plugin:1.0.0-beta4"` and after try to update `vendor` directory: `php composer.phar update` But however I'm not sure where this error is came for, so it's just some ideas.

**Comment by nvshivakumar** [comment]
ok
Both has done, but nope

**Comment by vova07** [comment]
Unfortunately then, the only way is to remove vendor directory.
Also need to check if installed extension work without problems.

**Comment by mhopkalo18** [comment]
It is trying to access [project]/vendor/bower/jquery/dist while jquery is installed into [project]/vendor/bower-asset/jquery/dist, maybe symlink can help you.

**Comment by bubbakk** [comment]
I have the same problem. I tried removing vendor directory and reinstalling using composer, but it does not fix the problem.
I fixed it creating a symlink in vendor directory: ln -s ./bower-asset/ ./bower
This works, but don't know if is a secure and good fix.

**Comment by ligexiao** [comment]
I have the same problem，I tried @bubbakk 's idea and it works~

**Comment by otireda** [comment]
I had the same problem. C:\wamp\www\yii2-start/vendor\bower/jquery/dist no found. 
I when to the diretory to verify if it exist and I found the name of diretory bower diferent "C:\wamp\www\basic/vendor\bower/bower-asset/jquery/dist" and I change it to C:\wamp\www\yii2-start/vendor\bower/jquery/dist. ANd problem solved.

WORK FOR ME

**Comment by krishna-complitech** [comment]
Hey otireda,
Thank you so very.
Its working.

**Comment by ZipDriver** [comment]
The same problem here. Also find jquery/dist under /bower/bower-asset directory but not under /bower. After move files to /bower all working fine, but "composer update" command again update files under /bower/bower-asset directory.

How to fix this issue with correct configuration?

**Comment by krishna-complitech** [comment]
Hey @ZipDriver 

No require to update composer.

**Comment by nekit44** [comment]
otireda, thanks

**Comment by pear2007** [comment]
Is look  like   var/www/html/basic/vendor/bower/jquery   empty

**Comment by BMCSamael** [comment]
yeah the entire thing went into bower-asset.. moved all files from there into bower and like a charm working.

**Comment by bossqito** [comment]
none of it works for me

**Comment by bossqito** [comment]
it there a way to install widgets on yii2 without using composer ?

**Comment by panyyer** [comment]
I think we can't just remove the folder, it may be lead to other problems

**Comment by omer-sds** [comment]
Is there any update on this issue?. I also have the same problem, though on local computer I have the bower directory but when i tried to setup the project on my staging server, composer install creates the directory with the name vendor/bower-assets/ rather than vendor/bower/ i remember i setup the project on my local computer a few weeks ago.
This problem may be any update to composer, yii, or bower itself because after thinking this i ran `composer update` on local computer to check if it replaces the bower with bower-assets, it updated all the plug-ins and extensions to the latest versions including the vendor/bower directory too but did'nt renamed it to vendor/bower-assets. 
The only difference i had is the composer itself, on local computer i have a version older than 60 days, and on live i installed composer through curl.
Waiting for a fix from you guys, currently what i am going to do is use the older version of composer.phar on staging server too so that i can get over this head-ache of renaming the directory from bower-assets to bower every time i update the composer to install any extension.

**Comment by ZipDriver** [comment]
Hello,

Yes, problem still in place. Unfortunately, no any updates was made.

Regards,
Andrejs.

**Comment by VenuNarukulla** [comment]
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /var/www/html/myproject/vendor/yiisoft/yii2/authclient/assets

**Comment by Bahmad92** [comment]
go to the directory C:\wamp64\www\yii2-advanced-api\vendor and change bower-asset into bower. this helped me.
