### ISSUE TITLE
symlink(): Cannot create symlink, error code(1314) 

### ISSUE THREAD

**Issue by auzankyu** [vova07/yii2-start#81]
hello im using windows and xampp to install yii2-start

why i have error code 1314 ?

**Comment by gopalkohli** [comment]
On IIS (Internet Information Services), you need to set permissions to allow the creation of symbolic links.

Go to Local Security Policy -> Local Policies -> User Rights Assignment and right click on Create symbolic links -> Properties -> Add User or Group and add the "IUSR" user, which should be the user associated with IIS.
A restart may be required.

If this doesn't work, go to IIS Manager -> Authentication -> select Anonymous Authentication -> Edit and enter your current logged in user, which should be an administrator.
Hit OK and now the symlink() function in php should work fine.

**Comment by pafcosta** [comment]
With EasyPHP, I started the server as "execute as administrator". It worked.

**Comment by jcfiorenzano** [comment]
open the xampp control with administrator priviligies and start the apache server, this solved the symlink problem with xampp and windows

**Comment by yonifine** [comment]
@jcfiorenzano thanks man! simple and clean. it worked!

**Comment by LeGlAndrelGend** [comment]
Thank you very much! I started my xampp by administrator.

**Comment by bogvsdev** [comment]
thanks! Launching as administrator works just fine!

**Comment by mhl130** [comment]
thanks
