### ISSUE TITLE
Вход в админ панель

### ISSUE THREAD

**Issue by alexssdd** [vova07/yii2-start#89]
При входе в админ панель если ввести правильный логин и пароль то с первого раза не заходит если повторно то проблем нету, если перейте на демо yii2-start.find-freelancer.pro/backend/login/ то аналогичная проблема.

**Comment by mCassy** [comment]
Добрый день. При входе в админку не отображается тема. Быть может, кто-нибудь сталкивался с такой проблемой ?

**Comment by vova07** [comment]
@mCassy Что именно вы видите? Можете предоставить скрин? Ошибки в консоли браузера есть? Рут приложения правильно настроили?

**Comment by mCassy** [comment]
@vova07 вот скрин. ![ddd](https://cloud.githubusercontent.com/assets/9416864/7025445/73810cbc-dd4c-11e4-91cb-9940017ade39.png)  ошибок не было. рут перепроверил. "передний конец" прекрасно работает.спасибо что ответили.

**Comment by vova07** [comment]
@mCassy  приведите пожалуйста кусок кода с вашими реальными настройками VHOSTS. Хочу убедится что это реально не проблема. Дальше будем смотреть.

**Comment by mCassy** [comment]
@vova07 вот настроечки
<VirtualHost *:80>
  ServerAlias 1devblog.zz www.1devblog.zz
  DocumentRoot /home/mosher/server/devblog.zz/backend/web
  <Directory home/mosher/server/devblog.zz/backend/web/>
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>

**Comment by mCassy** [comment]
@vova07 

```
<VirtualHost *:80>
  ServerAlias 1devblog.zz www.1devblog.zz
  DocumentRoot /home/mosher/server/devblog.zz/backend/web
  <Directory home/mosher/server/devblog.zz/backend/web/>
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>

```

**Comment by vova07** [comment]
При использовании `apache` вам нужно настроить рут демена на корневую папку всего приложения. То есть должно быть так:

```
<VirtualHost *:80>
  ServerAlias 1devblog.zz www.1devblog.zz
  DocumentRoot /home/mosher/server/devblog.zz
  <Directory home/mosher/server/devblog.zz>
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

**Comment by mCassy** [comment]
@vova07 спасибо=) все теперь работает. прошу извинить за глупые вопросы =))

**Comment by vova07** [comment]
Не за что! Удачного кодинга!

**Comment by mCassy** [comment]
@vova07 ,Благодарю. и Вам того же.
