### ISSUE TITLE
Override views.

### ISSUE THREAD

**Issue by nunomaduro** [vova07/yii2-start#94]
Hey, 

What is the best option to override views ?

Example: Override header, override mail change, etc.

**Comment by caceresvega** [comment]
Hello, I would like to know where to place the controller, model and view generated with crud in yii2-start. Because I have placed in the backend and I mouestra Page Not Found message. Thank you

**Comment by vova07** [comment]
Hi @caceresvega ,
You my put them to the default folders. Of course there are missed by default, but you can create them by your self. So models will be placed in `backend/models` and controllers in `backend/controllers` directory.
All like in `advanced` template.
Yes, and don't forgot to add the `URL` rule for your new controllers, something like: `'<_c>/<_a>' => '<_c>/<_a>'`
Good luck!

**Comment by caceresvega** [comment]
Thank worked properly

**Comment by caceresvega** [comment]
Dear I have tried to set yii2-start a hosting 1and1.com and I have not achieved it shows me the error of Internal Server Error and all paracer be a problem with the configuration of the .htaccess file (for locally works) thatYou have the following code:

# Mod_Autoindex

<IfModule mod_autoindex.c>
    # Disable Indexes
    Options -Indexes
</IfModule>

# Mod_Rewrite

<IfModule mod_rewrite.c>
    Options -Multiviews
    RewriteBase /

```
# Enable symlinks
Options +FollowSymlinks
# Enable mod_rewrite
RewriteEngine On

# Backend redirect
RewriteCond %{REQUEST_URI} ^/backend
RewriteRule ^backend/(.*)$ /backend/web/$1 [L]

# Statics redirect
RewriteCond %{REQUEST_URI} ^/statics
RewriteRule ^statics/(.*)$ /statics/web/$1 [L]

# Frontend redirect
RewriteCond %{REQUEST_URI} ^(.*)$
RewriteRule ^(.*)$ /backend/web/$1 [L]
```

</IfModule>

I would appreciate if you have any ideas to help me asolucionar this problem, have the url where the site is hosting de1and1.com http://qs.redbridgeinsurance.com

My email is: caceresvega@gmail.com
Thank you very much for the help you can give me
Juan Alberto Caceres Vega

**Comment by vova07** [comment]
Hi @caceresvega ,
What is the exact internal error that you got? Check the `log` file please on the server side, and provide some info about what's going wrong, because without any info I really can't help with anything.

**Comment by vova07** [comment]
Yes, and if it's possible, please create a new issue for this conversation.
It's not related with the current issue. I'll help you there.
